IssueComment
  { issueCommentUpdatedAt = 2013 (-09) (-26) 23 : 30 : 23 UTC
  , issueCommentUser =
      SimpleUser
        { simpleUserId = Id 552910
        , simpleUserLogin = N "Tryneus"
        , simpleUserAvatarUrl =
            "https://avatars.githubusercontent.com/u/552910?v=3"
        , simpleUserUrl = "https://api.github.com/users/Tryneus"
        , simpleUserType = OwnerUser
        }
  , issueCommentUrl =
      "https://api.github.com/repos/rethinkdb/rethinkdb/issues/comments/25212261"
  , issueCommentHtmlUrl =
      "https://github.com/rethinkdb/rethinkdb/issues/1483#issuecomment-25212261"
  , issueCommentCreatedAt = 2013 (-09) (-26) 23 : 30 : 23 UTC
  , issueCommentBody =
      "Ok, I ran into a bug when reproducing this.  Due to our string serialization changes, v1.10 would cause earlier versions of rethinkdb to crash when trying to connect to them.  This has been fixed in next in commit a1ba5ac, and cherry-picked into v1.10.x in commit b4e306f51a638fd3f36d4f10d3e027f97be29d1d (review 960).  I have also included in this change the remote peername.\r\n\r\nAs for this issue itself, the warning appears in the log of both rethinkdb instances (the one connecting and the one being connected to).  I believe this concludes the issue."
  , issueCommentId = 25212261
  }