IssueComment
  { issueCommentUpdatedAt = 2015 (-12) (-16) 07 : 54 : 42 UTC
  , issueCommentUser =
      SimpleUser
        { simpleUserId = Id 144498
        , simpleUserLogin = N "snackycracky"
        , simpleUserAvatarUrl =
            "https://avatars.githubusercontent.com/u/144498?v=3"
        , simpleUserUrl = "https://api.github.com/users/snackycracky"
        , simpleUserType = OwnerUser
        }
  , issueCommentUrl =
      "https://api.github.com/repos/rethinkdb/rethinkdb/issues/comments/165025928"
  , issueCommentHtmlUrl =
      "https://github.com/rethinkdb/rethinkdb/issues/4872#issuecomment-165025928"
  , issueCommentCreatedAt = 2015 (-12) (-16) 07 : 54 : 42 UTC
  , issueCommentBody =
      "I can just say that this happens also with 2.1.5 2.2.0 and 2.2.1. \r\nAs a workaround for now I am just running one instance because we are still in development mode. With a single server this error does not appear. Also I introduced rethinkdbdash to the project which might be a cause too. Sorry dont have more info."
  , issueCommentId = 165025928
  }