IssueComment
  { issueCommentUpdatedAt = 2014 (-08) (-05) 14 : 58 : 01 UTC
  , issueCommentUser =
      SimpleUser
        { simpleUserId = Id 4754399
        , simpleUserLogin = N "bigtree3131"
        , simpleUserAvatarUrl =
            "https://avatars.githubusercontent.com/u/4754399?v=3"
        , simpleUserUrl = "https://api.github.com/users/bigtree3131"
        , simpleUserType = OwnerUser
        }
  , issueCommentUrl =
      "https://api.github.com/repos/rethinkdb/rethinkdb/issues/comments/51209243"
  , issueCommentHtmlUrl =
      "https://github.com/rethinkdb/rethinkdb/issues/2703#issuecomment-51209243"
  , issueCommentCreatedAt = 2014 (-08) (-05) 14 : 58 : 01 UTC
  , issueCommentBody =
      "@coffeemug @danielmewes @srh @mglukhovsky , I just ran into the same issue (still on ext4 -- I plan on switching to ext3 before restoring) ... I have the log file and _usr_ rethinkdb.0.crash file -- this occurred during a db backup"
  , issueCommentId = 51209243
  }