Issue
  { issueClosedAt = Just 2016 (-08) (-22) 18 : 32 : 36 UTC
  , issueUpdatedAt = 2016 (-09) (-08) 01 : 33 : 31 UTC
  , issueEventsUrl =
      "https://api.github.com/repos/rethinkdb/rethinkdb/issues/6033/events"
  , issueHtmlUrl =
      Just "https://github.com/rethinkdb/rethinkdb/issues/6033"
  , issueClosedBy = Nothing
  , issueLabels =
      [ IssueLabel
          { labelColor = "e10c02"
          , labelUrl =
              "https://api.github.com/repos/rethinkdb/rethinkdb/labels/pr:high"
          , labelName = "pr:high"
          }
      , IssueLabel
          { labelColor = "e102d8"
          , labelUrl =
              "https://api.github.com/repos/rethinkdb/rethinkdb/labels/tp:bug"
          , labelName = "tp:bug"
          }
      ]
  , issueNumber = 6033
  , issueAssignee =
      Just
        SimpleUser
          { simpleUserId = Id 505365
          , simpleUserLogin = N "danielmewes"
          , simpleUserAvatarUrl =
              "https://avatars.githubusercontent.com/u/505365?v=3"
          , simpleUserUrl = "https://api.github.com/users/danielmewes"
          , simpleUserType = OwnerUser
          }
  , issueUser =
      SimpleUser
        { simpleUserId = Id 1430058
        , simpleUserLogin = N "ntquyen"
        , simpleUserAvatarUrl =
            "https://avatars.githubusercontent.com/u/1430058?v=3"
        , simpleUserUrl = "https://api.github.com/users/ntquyen"
        , simpleUserType = OwnerUser
        }
  , issueTitle =
      "One instance crashed in Rethinkdb 2.2.5 cluster, possible broken data"
  , issuePullRequest = Nothing
  , issueUrl =
      "https://api.github.com/repos/rethinkdb/rethinkdb/issues/6033"
  , issueCreatedAt = 2016 (-08) (-05) 04 : 22 : 23 UTC
  , issueBody =
      Just
        "I'm running rethinkdb 2.2.5 cluster of 3 instances:\n- OS: coreos 899.15.0 (Linux coreos-data-4 4.3.6-coreos #2 SMP Tue Apr 5 10:32:16 UTC 2016 x86_64 Intel(R) Xeon(R) CPU E5-2630 0 @ 2.30GHz GenuineIntel GNU/Linux)\n- Docker 1.9.1\n\nOne instance in the cluster suddenly crashed and cannot be restarted, backtrace: \n\n```\nRunning rethinkdb 2.2.5~0jessie (GCC 4.9.2)...\nRunning on Linux 4.3.6-coreos x86_64\nLoading data from directory /data\nListening for intracluster connections on port 29015\nConnected to server \"4200b06bc82a_1yx\" 83a15f4a-a772-4649-b866-d537e5c0cfba\nConnected to proxy ee2e9ad4-3bd7-48a0-ba3f-2c9406ac3d02\nConnected to server \"02f81613b7c1_wdx\" 8138c225-e59c-4e5c-8f2e-93a5689aea47\nListening for client driver connections on port 28015\nListening for administrative HTTP connections on port 8080\nListening on addresses: 127.0.0.1, 10.2.44.2, ::1, fe80::42:aff:fe02:2c02%5\nServer ready, \"c1d17389be71_29y\" d5a8f7d7-33b2-4f60-9561-38d4a9d163e1\nA newer version of the RethinkDB server is available: 2.3.4. You can read the changelog at <https://github.com/rethinkdb/rethinkdb/releases>.\nVersion: rethinkdb 2.2.5~0jessie (GCC 4.9.2)\nerror: Error in src/rdb_protocol/serialize_datum.cc at line 814:\nerror: Guarantee failed: [datum_deserialize(&read_stream, &type) == archive_result_t::SUCCESS] Deserialization of datum type from buf failed with error archive_result_t::RANGE_ERROR.\nerror: Backtrace:\nerror: Fri Aug  5 03:52:04 2016\n\n       1 [0xa8b7f0]: backtrace_t::backtrace_t() at 0xa8b7f0 (rethinkdb)\n       2 [0xa8bb69]: format_backtrace(bool) at 0xa8bb69 (rethinkdb)\n       3 [0xd0135d]: report_fatal_error(char const*, int, char const*, ...) at 0xd0135d (rethinkdb)\n       4 [0x92f080]: ql::datum_deserialize_from_buf(shared_buf_ref_t<char> const&, unsigned long) at 0x92f080 (rethinkdb)\n       5 [0x92f656]: ql::datum_deserialize_pair_from_buf(shared_buf_ref_t<char> const&, unsigned long) at 0x92f656 (rethinkdb)\n       6 [0x8d3329]: ql::datum_t::unchecked_get_pair(unsigned long) const at 0x8d3329 (rethinkdb)\n       7 [0x8d60fb]: rethinkdb() [0x8d60fb] at 0x8d60fb ()\n       8 [0x8d61d0]: ql::datum_t::is_ptype() const at 0x8d61d0 (rethinkdb)\n       9 [0x87668b]: ql::obj_or_seq_op_impl_t::eval_impl_dereferenced(ql::term_t const*, ql::scope_env_t*, ql::args_t*, scoped_ptr_t<ql::val_t> const&, std::function<scoped_ptr_t<ql::val_t> ()>) const at 0x87668b (rethinkdb)\n       10 [0x87952f]: ql::bracket_term_t::eval_impl(ql::scope_env_t*, ql::args_t*, ql::eval_flags_t) const at 0x87952f (rethinkdb)\n       11 [0x7d0952]: ql::op_term_t::term_eval(ql::scope_env_t*, ql::eval_flags_t) const at 0x7d0952 (rethinkdb)\n       12 [0x8ea64a]: ql::runtime_term_t::eval_on_current_stack(ql::scope_env_t*, ql::eval_flags_t) const at 0x8ea64a (rethinkdb)\n       13 [0x8ea94c]: ql::runtime_term_t::eval(ql::scope_env_t*, ql::eval_flags_t) const at 0x8ea94c (rethinkdb)\n       14 [0x7cd19a]: ql::op_term_t::maybe_grouped_data(ql::scope_env_t*, ql::argvec_t*, ql::eval_flags_t, counted_t<ql::grouped_data_t>*, scoped_ptr_t<ql::val_t>*) const at 0x7cd19a (rethinkdb)\n       15 [0x7d030b]: ql::op_term_t::term_eval(ql::scope_env_t*, ql::eval_flags_t) const at 0x7d030b (rethinkdb)\n       16 [0x8ea64a]: ql::runtime_term_t::eval_on_current_stack(ql::scope_env_t*, ql::eval_flags_t) const at 0x8ea64a (rethinkdb)\n       17 [0x8ea94c]: ql::runtime_term_t::eval(ql::scope_env_t*, ql::eval_flags_t) const at 0x8ea94c (rethinkdb)\n       18 [0x80ddcb]: ql::reql_func_t::call(ql::env_t*, std::vector<ql::datum_t, std::allocator<ql::datum_t> > const&, ql::eval_flags_t) const at 0x80ddcb (rethinkdb)\n       19 [0x80d436]: ql::func_t::call(ql::env_t*, ql::datum_t, ql::eval_flags_t) const at 0x80d436 (rethinkdb)\n       20 [0x7b8383]: compute_keys(store_key_t const&, ql::datum_t, sindex_disk_info_t const&, std::vector<std::pair<store_key_t, ql::datum_t>, std::allocator<std::pair<store_key_t, ql::datum_t> > >*) at 0x7b8383 (rethinkdb)\n       21 [0x7b9fb3]: rdb_update_single_sindex(store_t*, store_t::sindex_access_t const*, deletion_context_t const*, rdb_modification_report_t const*, unsigned long*, auto_drainer_t::lock_t, cond_t*, std::vector<std::pair<ql::datum_t, boost::optional<unsigned long> >, std::allocator<std::pair<ql::datum_t, boost::optional<unsigned long> > > >*, std::vector<std::pair<ql::datum_t, boost::optional<unsigned long> >, std::allocator<std::pair<ql::datum_t, boost::optional<unsigned long> > > >*) at 0x7b9fb3 (rethinkdb)\n       22 [0x7c2559]: callable_action_instance_t<std::_Bind<void (*(store_t*, store_t::sindex_access_t*, deletion_context_t const*, rdb_modification_report_t const*, unsigned long*, auto_drainer_t::lock_t, cond_t*, std::vector<std::pair<ql::datum_t, boost::optional<unsigned long> >, std::allocator<std::pair<ql::datum_t, boost::optional<unsigned long> > > >*, std::vector<std::pair<ql::datum_t, boost::optional<unsigned long> >, std::allocator<std::pair<ql::datum_t, boost::optional<unsigned long> > > >*))(store_t*, store_t::sindex_access_t const*, deletion_context_t const*, rdb_modification_report_t const*, unsigned long*, auto_drainer_t::lock_t, cond_t*, std::vector<std::pair<ql::datum_t, boost::optional<unsigned long> >, std::allocator<std::pair<ql::datum_t, boost::optional<unsigned long> > > >*, std::vector<std::pair<ql::datum_t, boost::optional<unsigned long> >, std::allocator<std::pair<ql::datum_t, boost::optional<unsigned long> > > >*)> >::run_action() at 0x7c2559 (rethinkdb)\n       23 [0x99c958]: coro_t::run() at 0x99c958 (rethinkdb)\nerror: Exiting.\n```\n\nWhen the crash occurred, `systemd-coredum` took all the CPU and cannot be stopped unless I stop the rethinkdb container and restart the server. After the server restarted and `systemd-coredum` disabled, rethinkdb still cannot be started, same crash.\n\nIt is likely the data is somehow broken (Deserialization failed). I'm have 10 rethinkdb clusters running in production but this is the first time I got this issue.\n"
  , issueState = "closed"
  , issueId = Id 169525860
  , issueComments = 9
  , issueMilestone =
      Just
        Milestone
          { milestoneCreator =
              SimpleUser
                { simpleUserId = Id 505365
                , simpleUserLogin = N "danielmewes"
                , simpleUserAvatarUrl =
                    "https://avatars.githubusercontent.com/u/505365?v=3"
                , simpleUserUrl = "https://api.github.com/users/danielmewes"
                , simpleUserType = OwnerUser
                }
          , milestoneDueOn = Just 2016 (-08) (-04) 07 : 00 : 00 UTC
          , milestoneOpenIssues = 0
          , milestoneNumber = 126
          , milestoneClosedIssues = 39
          , milestoneDescription = Just ""
          , milestoneTitle = "2.3.5"
          , milestoneUrl =
              "https://api.github.com/repos/rethinkdb/rethinkdb/milestones/126"
          , milestoneCreatedAt = 2016 (-07) (-28) 21 : 38 : 16 UTC
          , milestoneState = "closed"
          }
  }