IssueComment
  { issueCommentUpdatedAt = 2013 (-06) (-30) 03 : 00 : 43 UTC
  , issueCommentUser =
      SimpleUser
        { simpleUserId = Id 1461947
        , simpleUserLogin = N "neumino"
        , simpleUserAvatarUrl =
            "https://avatars.githubusercontent.com/u/1461947?v=3"
        , simpleUserUrl = "https://api.github.com/users/neumino"
        , simpleUserType = OwnerUser
        }
  , issueCommentUrl =
      "https://api.github.com/repos/rethinkdb/rethinkdb/issues/comments/20241231"
  , issueCommentHtmlUrl =
      "https://github.com/rethinkdb/rethinkdb/issues/1097#issuecomment-20241231"
  , issueCommentCreatedAt = 2013 (-06) (-30) 02 : 59 : 19 UTC
  , issueCommentBody =
      "Note that the query that broke the server is\r\n\r\n```python\r\nr.db('race_events').table('locations').update(\r\n  r.js('(function(row){return {lat:parseFloat(row.lat), long:parseFloat(row.long)};})'),\r\n  non_atomic=True\r\n)\r\n```\r\n\r\nI just tested it and it works fine (on a well defined set -- I haven' t try with undefined/unexpected values).\r\n\r\n"
  , issueCommentId = 20241231
  }