IssueComment
  { issueCommentUpdatedAt = 2015 (-11) (-10) 20 : 03 : 10 UTC
  , issueCommentUser =
      SimpleUser
        { simpleUserId = Id 505365
        , simpleUserLogin = N "danielmewes"
        , simpleUserAvatarUrl =
            "https://avatars.githubusercontent.com/u/505365?v=3"
        , simpleUserUrl = "https://api.github.com/users/danielmewes"
        , simpleUserType = OwnerUser
        }
  , issueCommentUrl =
      "https://api.github.com/repos/rethinkdb/rethinkdb/issues/comments/155549974"
  , issueCommentHtmlUrl =
      "https://github.com/rethinkdb/rethinkdb/issues/5069#issuecomment-155549974"
  , issueCommentCreatedAt = 2015 (-11) (-10) 20 : 03 : 10 UTC
  , issueCommentBody =
      "Thanks for the report @keshavagrawal89 .\r\nI haven't seen this error before. @deontologician do you have any ideas?\r\n\r\nOne thing to make sure is that you don't call `pool.release` on a connection before you've read all data from a cursor. To be safe, you might might also want to call `close()` on the cursor (not on the connection) before releasing the connection back into the pool."
  , issueCommentId = 155549974
  }